<a href="https://colab.research.google.com/github/ianbennett41430/ICP3.1/blob/main/ICP3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part 1.a


In [ ]:
#imports numpy
import numpy as np
#makes a random vector
random_vector = np.random.randint(1, 21, size=15)

#reshapes the vector
reshaped_array = random_vector.reshape(3, 5)

#prints the shape of the array
print("Shape of the array:", reshaped_array.shape)

#prints the random array
print("Random array: \n", reshaped_array)

#replaces the largest value with 0
reshaped_array[np.arange(len(reshaped_array)), np.argmax(reshaped_array, axis=1)] = 0

#prints modified array
print("Array after replacing max in each row by 0:\n", reshaped_array)


Shape of the array: (3, 5)
Random array: 
 [[10 20 15 14 12]
 [ 4 11 16 13  7]
 [ 6 10  3  9 10]]
Array after replacing max in each row by 0:
 [[10  0 15 14 12]
 [ 4 11  0 13  7]
 [ 6  0  3  9 10]]


Part 1.b

In [ ]:
import numpy as np
#builds the array
array = np.array([[3, -2],
                  [1, 0]])
#calculates eigenvalues and right eigenvectors of the array
eigenvalues, eigenvectors = np.linalg.eig(array)

#prints the eigenvalues and right eigenvectors
print("Eigenvalues:", eigenvalues)
print("Right Eigenvectors:", eigenvectors)


Eigenvalues: [2. 1.]
Right Eigenvectors: [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


Part 1.c

In [ ]:
import numpy as np
#builds the array
array = np.array([[0, 1, 2],
                  [3, 4, 5]])
#calculates the diagnal sum
diagonal_sum = np.trace(array)

#prints the sum of the diagnals
print("Sum of diagonal elements:", diagonal_sum)


Sum of diagonal elements: 4


Part 1.d

In [ ]:
import numpy as np
#builds the array
array = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])
#reshapes the array to a 2x3
reshaped_array_1 = np.reshape(array, (2, 3))

#reshapes the array to a 3x2
reshaped_array_2 = np.reshape(array, (3, 2))

#prints both arrays
print("Reshaped array 1 (2x3):\n", reshaped_array_1)
print("Reshaped array 2 (3x2):\n", reshaped_array_2)


Reshaped array 1 (2x3):
 [[1 2 3]
 [4 5 6]]
Reshaped array 2 (3x2):
 [[1 2]
 [3 4]
 [5 6]]


Part 2

In [ ]:
import pandas as pd

#imports csv
df = pd.read_csv("data.csv")

#shows basic statistical description
description = df.describe()
print("Basic Statistical Description:")
print(description)

#checks for null values
print("\nNull values check:")
print(df.isnull().sum())

#replaces null values with the mean
df.fillna(df.mean(), inplace=True)

#finds aggregate data of the last 2 columns using min, max, count, mean for two columns
aggregated_data = df[['Duration', 'Pulse']].agg(['min', 'max', 'count', 'mean'])
print("\nAggregated Data:")
print(aggregated_data)

#filters rows with calories values between 500 and 1000
calories_filter = df[(df['Calories'] >= 500) & (df['Calories'] <= 1000)]

#filters rows with calories values > 500 and pulse < 100
filter_condition = (df['Calories'] > 500) & (df['Pulse'] < 100)
filtered_df = df[filter_condition]

#creates new df_modified dataframe without maxpulse
df_modified = df.drop(columns=['Maxpulse'])

#deleates maxpuse
df.drop(columns=['Maxpulse'], inplace=True)

#converts datatype of calories to int
df['Calories'] = df['Calories'].astype(int)

#prints a sample of the dataframes
print("\nSample of df_modified dataframe:")
print(df_modified.head())

print("\nSample of df dataframe after modifications:")
print(df.head())


Basic Statistical Description:
         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

Null values check:
Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

Aggregated Data:
         Duration       Pulse
min     15.000000   80.000000
max    300.000000  159.000000
count  169.000000  169.000000
mean    63.846154  107.461538

Sample of df_modified dataframe:
   Duration  Pulse  Calories
0        60    110     409.1
1        60    117     479.0
2        60    103     340.0
3        45    109     282.4
4        45    117     406.0

Sample o